# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20180514_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('logintime', models.DateField()),
            ],
        ),
    ]
