# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='logintime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
