# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('actiontime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
